ReadMesh 1 /Users/josea/PhD/Magnetite/q1_T20/mesh/x100_y100_z100/x100_y100_z100.pat

Magnetite 20 C
Minimize 
External Field Direction 1 1 1
External field strength 0 mT
Loop field 300 -300 -5
	External field strength $field$ mT
	Randomize Magnetization 5
	Minimize
	WriteMagnetization /Users/josea/PhD/Magnetite/q1_T20/hyst/ground/x100_y100_z100/x100_y100_z100_T20/Hx0.577_Hy0.577_Hz0.577/Hx0.577_Hy0.577_Hz0.577_$field$mT
	WriteHyst /Users/josea/PhD/Magnetite/q1_T20/hyst/hyst/x100_y100_z100/x100_y100_z100_T20/Hx0.577_Hy0.577_Hz0.577/Hx0.577_Hy0.577_Hz0.577
EndLoop
